CRUD operations for products
Xeragus/nodejs-gen-15 pull request #5
Opened 2022-03-23 21:14 UTC by alekvan

New endpoint handlers for products route

2022-03-23 21:17 UTC, bobansugareski commented on social-app/app.js
> +// require('dotenv').config();
Unnecessary line

2022-03-23 21:17 UTC, bobansugareski requested changes

2022-03-23 21:17 UTC, bobansugareski commented on social-app/models/products.js
> +module.exports = mongoose.model('products', productsSchema);
```suggestion
module.exports = mongoose.model('product', productsSchema);
```

2022-03-23 21:19 UTC, bobansugareski commented on social-app/controllers/products.js
> +const Product = require('../models/products');
```suggestion
const Product = require('../models/product');
```

2022-03-23 21:25 UTC, bobansugareski commented on social-app/app.js
> +// require('dotenv').config();
Revert the change here

2022-03-23 22:49 UTC, alekvan commented on social-app/app.js
> +// require('dotenv').config();
Fixed

2022-03-23 22:49 UTC, alekvan commented on social-app/controllers/products.js
> +const Product = require('../models/products');
Fixed

2022-03-23 22:50 UTC, alekvan commented on social-app/models/products.js
> +module.exports = mongoose.model('products', productsSchema);
Fixed

2022-03-24 13:52 UTC, bobansugareski approved these changes

2022-03-24 20:43 UTC, stefanaleksovski1999 approved these changes

2022-03-24 20:43 UTC, merged